# Generated by Django 2.1.5 on 2019-06-05 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_campaign_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='added_by',
            field=models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
